### ISSUE TITLE
View template error when using ng2-pdf-viewer in Angular v13.3.11

### ISSUE THREAD

**Issue by mmgarrido** [VadimDez/ng2-pdf-viewer#909]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I'm getting compilation error in the view template on this line.
`<pdf-viewer [src]="pdfSrc">`

The error message is:
```
Type 'string | PDFSource | ArrayBuffer' is not assignable to type 'string | Uint8Array | PDFSource'.
  Type 'ArrayBuffer' is not assignable to type 'string | Uint8Array | PDFSource'.
    Type 'ArrayBuffer' is missing the following properties from type 'Uint8Array': BYTES_PER_ELEMENT, buffer, byteOffset, copyWithin, and 23 more.

```
I tried using the following versions of ng2-pdf-viewer: v9.0.0, v7.0.2, v6.4.1. All these versions fail with the same error.
Version 6.4.1 works with Angular v7.3

What do you think is my error? Any help would be greatly appreciated. Thanks in advance.

Below is my dev environment.
```
Angular CLI: 13.3.0
Node: 16.16.0
Package Manager: npm 8.11.0
OS: darwin arm64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.0
@angular-devkit/build-angular   13.3.8
@angular-devkit/core            13.3.0
@angular-devkit/schematics      13.3.0
@angular/cdk                    13.3.9
@angular/cli                    13.3.0
@angular/material               13.3.9
@schematics/angular             13.3.0
rxjs                            7.5.6
typescript                      4.6.4
```

**Comment by mmgarrido** [comment]
Since in my use case pdfSrc is a string, my temporary solution to this problem is to declare pdfSrc as a string in the offending line, like so:

```
//  public pdfSrc: string | PDFSource | ArrayBuffer = 'assets/pdf/cp.pdf';
    public pdfSrc: string = 'assets/pdf/cp.pdf';

```
