### ISSUE TITLE
ERROR in node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:5:13 - error TS1005: '=' expected.

### ISSUE THREAD

**Issue by justwooper** [VadimDez/ng2-pdf-viewer#785]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X ] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I have this bugs when I try to use the plugin:

ERROR in node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:5:13 - error TS1005: '=' expected.

5 import type { PDFSource, PDFProgressData } from './typings';
              ~
node_modules/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.d.ts:5:49 - error TS1005: ';' expected.

5 import type { PDFSource, PDFProgressData } from './typings';

"rxjs": "6.5.4",
"typescript": "^3.7.5"

**Comment by justwooper** [comment]
Hi, sure

"tslib": "1.10.0",
***@***.***/cli": "9.1.7",

**Comment by VadimDez** [comment]
That's what I thought! Starting version `7.0.0` `ng2-pdf-viewer` uses `tslib ^2.0.0`. You have two options - either to update your project to use `tslib ^2.0.0` or to use `ng2-pdf-viewer 6.4.1`.

**Comment by justwooper** [comment]
Thank you for your response

**Comment by WilliamTepet** [comment]
I was struggling with the same issue regarding the versions:

` "tslib": "^1.10.0"`
` "@angular/cli": "^9.0.7"`

so, I just downgrade to `ng2-pdf-viewer 6.4.1` and now it works without problems!

@VadimDez Thanks for the headlight!

**Comment by RamonPortales** [comment]
Hi guys, Is it possible to do this, or how can I do it ?

`this.pdfSrc = response.bytes;`  <---MyComponent  (response.bytes is a byte[ ] )

`<pdf-viewer [src]="pdfSrc"
              [render-text]="true"
              style="display: block;"
  ></pdf-viewer>`   <--- my html file

**Comment by himajaM** [comment]
Hi @VadimDez 
Facing an issue during Staging/Prod deployment after working with ng2-pdf-viewer 6.4.1 version I.e.,

**ERROR in ./node_modules/ng2-pdf-viewer/fesm5/ng2-pdf-viewer.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (.\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (.\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (.\node_modules\typescript\lib\typescript.js:16144:30)**
    
   Currently, I am working with 
   angular cli version is - "@angular/cli": "^7.2.3",
   "tslib": "^1.9.0",
   "zone.js": "^0.10.3"
   "rxjs": "^6.3.3",
    "@angular-devkit/build-angular": "^0.12.3",

I have tried installing the package pdfjs-dist@2.2.228 but still the issue exists... Could you please let me know how to resolve this...
