### ISSUE TITLE
Angular 10 update Karma unit test compilation error

### ISSUE THREAD

**Issue by rickvandermey** [VadimDez/ng2-pdf-viewer#630]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
When updating from Angular 9 to 10, the Unit test (karma) will not succeed anymore due to errors provided by ng2-pdf-viewer.

Module
```
import { CommonModule } from '@angular/common';
import { CUSTOM_ELEMENTS_SCHEMA, NgModule } from '@angular/core';
import { PdfViewerModule } from 'ng2-pdf-viewer';

import { SharedModule } from '@modules/shared.module';
import { CarouselModule } from 'ngx-bootstrap/carousel';
import { BsModalRef, ModalModule } from 'ngx-bootstrap/modal';
import { FileModalComponent } from './file-modal.component';

/**
 * Class representing the Modal component module
 */
@NgModule({
	declarations: [FileModalComponent],
	exports: [FileModalComponent],
	imports: [
		CarouselModule,
		CommonModule,
		ModalModule.forRoot(),
		PdfViewerModule,
		SharedModule,
	],
	providers: [BsModalRef],
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
/* istanbul ignore next */
export class FileModalModule {}
```

HTML
```
		<ng-container *ngIf="file.dataType === 'pdf'">
			<div class="content-container">
				<pdf-viewer
					[src]="file.dataUrl"
					[original-size]="false"
					[fit-to-page]="true"
				></pdf-viewer>
			</div>
		</ng-container>
```

SPEC
```
describe('Component: FileModal', () => {
	let component: any;
	let fixture: ComponentFixture<Component>;

	beforeEach(async(() => {
		TestBed.configureTestingModule({
			declarations: [Component],
			imports: [
				CarouselModule.forRoot(),
				CommonModule,
				TranslateModule.forChild({}),
			],
			providers: [TranslateService, TranslateStore],
			schemas: [CUSTOM_ELEMENTS_SCHEMA],
		}).compileComponents();

		fixture = TestBed.createComponent(Component);
		component = fixture.debugElement.componentInstance;
	}));

	it('should create the FileModal', async(() => {
		expect(component).toBeTruthy();
	}));
});
```

Error:
`Error during loading: Uncaught TypeError: Cannot set property 'pdfjsLib' of undefined in http://localhost:9876/_karma_webpack_/vendor.js line 240209`

CMD Error:
```
Chrome 84.0.4147.68 (Mac OS 10.15.5) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: Cannot set property 'pdfjsLib' of undefined
  TypeError: Cannot set property 'pdfjsLib' of undefined
      at webpackUniversalModuleDefinition (http://localhost:9876/_karma_webpack_/pdfjs-dist/build/pdf/webpack/universalModuleDefinition:9:1)
      at Module.<anonymous> (http://localhost:9876/_karma_webpack_/pdfjs-dist/build/pdf/webpack/universalModuleDefinition:1:1)
      at Module../node_modules/pdfjs-dist/build/pdf.js (http://localhost:9876/_karma_webpack_/vendor.js:255595:30)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
      at Module../node_modules/ng2-pdf-viewer/__ivy_ngcc__/fesm2015/ng2-pdf-viewer.js (http://localhost:9876/_karma_webpack_/ng:/ng2-pdf-viewer/src/app/pdf-viewer/pdf-viewer.component.ts:37:11)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
      at Object../src/app/components/modal/file-modal/file-modal.module.ts (http://localhost:9876/_karma_webpack_/main.js:29126:50)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
      at Object../src/app/components/modal/modal.module.ts (http://localhost:9876/_karma_webpack_/main.js:31379:53)
      at __webpack_require__ (http://localhost:9876/_karma_webpack_/webpack/bootstrap:79:1)
Chrome 84.0.4147.68 (Mac OS 10.15.5): Executed 0 of 0 ERROR (0 secs / 0 secs)
```

**Comment by PedroS5499** [comment]
i have same issue but in build
`Uncaught TypeError: Cannot set property 'pdfjsLib' of undefined
    at webpackUniversalModuleDefinition (vendor.js:687730)
    at Module.<anonymous> (vendor.js:687731)
    at Module../node_modules/pdfjs-dist/build/pdf.js (vendor.js:703116)
    at __webpack_require__ (runtime.js:85)
    at Module../node_modules/ng2-pdf-viewer/__ivy_ngcc__/fesm2015/ng2-pdf-viewer.js (vendor.js:686825)
    at __webpack_require__ (runtime.js:85)
    at Module../src/app/shared/modules/document-file/components/document-file-preview/document-file-preview.component.ts (main.js:14751)
    at __webpack_require__ (runtime.js:85)
    at Module../src/app/shared/modules/document-file/dialogs/dialog-document-file-editor/dialog-document-file-editor.component.ts (main.js:15598)
    at __webpack_require__ (runtime.js:85)`

**Comment by PedroS5499** [comment]
AOT

**Comment by rickvandermey** [comment]
any update from @VadimDez
